export const RAPID_TEST = `# /rapid-test — Rapid Idea Test

## What This Does

Takes a raw business idea, runs compressed research (5-8 searches), and generates a deployable landing page + ad copy in a single pass. Designed for testing 5-10 ideas quickly before committing to the full pipeline.

## Trigger Context
User has a business idea to test quickly. They do NOT want the full pipeline yet — they want signal before investing time. Trigger phrases: "rapid test" / "quick test this idea" / "test this fast" / "rapid-test [idea]" / user wants to test multiple ideas.

## Execution Protocol

### Step 0: Check Learnings
Silently check \`learnings.json\` for any patterns relevant to this market/idea category (market_selection, creative patterns). If relevant patterns exist, pass them to the subagent as additional context. If none exist, proceed without mentioning the check.

### Step 1: Receive the Idea
Accept the business idea in any format:
- A sentence: "I want to test selling a meal prep course for truck drivers"
- A market: "truck driver nutrition"
- A problem: "truck drivers struggle to eat healthy on the road"
- A product concept: "weekly meal prep kit designed for truck stop microwaves"

If critically ambiguous (cannot determine target audience OR core problem), ask ONE clarifying question. Otherwise, proceed immediately.

### Step 2: Set Test Parameters
Present defaults and ask for confirmation or changes:

\`\`\`
RAPID TEST SETUP — [Idea Name]

Defaults (press enter to accept, or specify changes):
  Budget: $75 ($15/day x 5 days)
  Duration: 5 days
  Offer type: Email capture (waitlist / lead magnet)
  Price point: N/A (email capture)

Want to change any of these? Or should I proceed?
\`\`\`

Alternative configurations:
- Direct sale: User specifies price. Default $47 (info product) or $97 (course/program).
- Longer test: $100 over 7 days ($14/day). Use for markets where buyer consideration time is longer.
- Shorter test: $50 over 3 days ($17/day). Use for impulse/pain-urgent markets.

If user says "just go" or gives no modifications, use defaults.

### Step 3: Generate Market Slug
Create a URL-safe slug from the idea: lowercase, hyphenated, no special characters. Examples:
- "meal prep for truck drivers" → \`meal-prep-truck-drivers\`
- "anxiety management for new moms" → \`anxiety-new-moms\`
- "Excel training for accountants" → \`excel-training-accountants\`

### Step 4: Delegate to Subagent

**DELEGATE TO SUBAGENT: \`rapid-tester\`**

Pass to subagent:
- The business idea/market seed (exact user input)
- Test parameters (budget, duration, offer type, price point)
- Market slug
- Any relevant learnings from learnings.json
- Today's date

Output directory: \`assets/[market-slug]/rapid-test/\`

### Step 5: Receive and Save Assets

Confirm all 4 subagent files saved to \`assets/[market-slug]/rapid-test/\`:
- \`buyer-snapshot.md\`
- \`landing-page.html\`
- \`ad-copy.md\`
- \`deployment-checklist.md\`

(The 5th file, \`decision-thresholds.md\`, is generated by the main command in Step 6 below.)

### Step 6: Generate Decision Thresholds

Based on budget and offer type, compute and save thresholds.

**For Email Capture / Lead Magnet tests:**
\`\`\`
RAPID TEST DECISION THRESHOLDS — [Idea Name]
Budget: $[X] | Duration: [Y] days | Offer: Email Capture

GRADUATE (strong signal — move to full pipeline):
  - Email signups: 10+ total
  - Cost per signup: <$[budget/10]
  - Landing page conversion rate: >15% from ad clicks
  - CTR on at least one ad variation: >1.5%
  - Qualitative bonus: signups reply to welcome email, ask questions

CONTINUE (some signal — extend or adjust):
  - Email signups: 3-9 total
  - Cost per signup: $[budget/10] - $[budget/5]
  - CTR on at least one ad: 0.8% - 1.5%
  - Some engagement but below graduation threshold

KILL (no signal — next idea):
  - <3 signups after full budget spent
  - CTR below 0.8% on ALL ads after 1,000+ impressions
  - Zero engagement signals (no clicks, no form starts)
  - $[budget/2]+ spent with zero conversions = early kill

UNIVERSAL KILL SIGNALS:
  - Zero clicks after 2,000+ impressions = invisible offer
  - CTR >2% but zero conversions from 50+ clicks = landing page problem (consider adjusting page, not killing)
\`\`\`

**For Direct Sale tests:**
\`\`\`
RAPID TEST DECISION THRESHOLDS — [Idea Name]
Budget: $[X] | Duration: [Y] days | Offer: Direct Sale at $[price]

GRADUATE:
  - Any completed sale = strong signal at this budget level
  - 2+ sales = near-certain graduation
  - CTR >1.5% + add-to-cart/checkout initiation >5%

CONTINUE:
  - CTR >1.5% but no completed sale (landing page/price issue, not demand)
  - Add-to-cart or checkout initiated but abandoned (trust or price friction)
  - High engagement metrics but no conversion (adjust offer, don't kill market)

KILL:
  - CTR <0.8% across ALL ad variations (targeting or pain mismatch)
  - Clicks but <1% landing page engagement (complete message mismatch)
  - No clicks after 2,000+ impressions (wrong audience or invisible creative)
\`\`\`

Save to: \`assets/[market-slug]/rapid-test/decision-thresholds.md\`

### Step 7: Create Rapid Test Pipeline Entry

Check if \`rapid_tests\` key exists in pipeline-state.json. If not, create it as an empty object.

Add entry. Compute threshold values based on offer type:
- **Email capture**: min_conversions graduate=10, continue=3; max_cost_per_conversion graduate=budget/10, continue=budget/5; min_landing_page_conversion graduate=15
- **Direct sale**: min_conversions graduate=1, continue=0; max_cost_per_conversion graduate=budget; min_landing_page_conversion graduate=5
- **Both types**: kill max_spend_zero_conversions = budget * 0.67

\`\`\`json
{
  "[market-slug]": {
    "idea": "[original idea description]",
    "market_slug": "[market-slug]",
    "created": "[today's date]",
    "status": "ready_to_deploy",
    "test_parameters": {
      "budget": 0,
      "daily_budget": 0,
      "duration_days": 0,
      "offer_type": "[email_capture|direct_sale]",
      "price_point": null
    },
    "thresholds": {
      "graduate": {
        "min_conversions": 0,
        "max_cost_per_conversion": 0,
        "min_ctr": 1.5,
        "min_landing_page_conversion": 0
      },
      "continue": {
        "min_conversions": 0,
        "max_cost_per_conversion": 0,
        "min_ctr": 0.8
      },
      "kill": {
        "max_spend_zero_conversions": 0,
        "min_ctr_after_1000_impressions": 0.8
      }
    },
    "deployment": {
      "landing_page_url": null,
      "campaign_live": false,
      "start_date": null,
      "end_date": null
    },
    "daily_checks": [],
    "aggregate_metrics": {
      "total_spend": 0,
      "total_impressions": 0,
      "total_clicks": 0,
      "total_conversions": 0,
      "ctr": null,
      "cpc": null,
      "cpa": null,
      "conversion_rate": null
    },
    "verdict": null,
    "graduated_to": null,
    "output_files": [
      "assets/[market-slug]/rapid-test/buyer-snapshot.md",
      "assets/[market-slug]/rapid-test/landing-page.html",
      "assets/[market-slug]/rapid-test/ad-copy.md",
      "assets/[market-slug]/rapid-test/deployment-checklist.md",
      "assets/[market-slug]/rapid-test/decision-thresholds.md"
    ]
  }
}
\`\`\`

### Step 8: Present Summary to User

\`\`\`
RAPID TEST READY — [Idea Name]

Research complete. Assets generated:
  ✓ Buyer Snapshot: [top pain point in buyer language — one line preview]
  ✓ Landing Page: HTML ready to deploy (signal-capture page)
  ✓ Ad Copy: [N] Meta variations (pain / failed-solution / promise / contrarian angles)
  ✓ Deployment Checklist: [N] steps, ~20-30 minutes setup
  ✓ Decision Thresholds: graduate / continue / kill criteria computed

Test Parameters:
  Budget: $[X] over [Y] days ($[daily]/day)
  Offer: [Email capture / Direct sale at $Z]
  Graduation: [key graduation metric]
  Kill: [key kill metric]

Files saved to: assets/[market-slug]/rapid-test/

NEXT:
  1. Follow the deployment checklist to get live (~20-30 min)
  2. Run /rapid-check daily with your ad manager numbers
  3. Decision on Day [Y]: graduate, continue, or kill

To see all your rapid tests: /rapid-status
\`\`\`

## Autonomy
Tier 1 — Full Auto for research and asset generation.
Tier 2 — Notify & Proceed for presenting the package.
User executes deployment manually at their own pace.

## Output
Complete rapid test package in \`assets/[market-slug]/rapid-test/\` (5 files). Summary presented inline.

## Next Step
User deploys (follows checklist) → runs \`/rapid-check\` daily → final verdict at end of window.
If user wants to test another idea simultaneously → run \`/rapid-test [next idea]\`.`;
